apiVersion: v1
kind: ConfigMap
metadata:
  name: rs-sapig-deployment-config
data:
  BASE_FQDN: "devops-core.forgerock.financial"
  IDENTITY_PLATFORM_FQDN: "iam.devops-core.forgerock.financial"
  AS_FQDN: "as-sapig.devops-core.forgerock.financial"
  RS_FQDN: "rs-sapig.devops-core.forgerock.financial"
  TRUSTEDDIR_FQDN: "test-trusted-directory.devops-core.forgerock.financial"