apiVersion: v1
kind: ConfigMap
metadata:
  name: core-deployment-config
data:
  #Fully Qualified Domain Names
  BASE_FQDN: dev.forgerock.financial
  IG_FQDN: sapig.dev.forgerock.financial
  MTLS_FQDN: mtls.sapig.dev.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.dev.forgerock.financial

  # Environment Settings for SAPIG & Cloud Platform
  # SAPIG
  # core: base sapig
  # ob: Open Banking specification of sapig
  SAPIG_TYPE: core
  # Cloud
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model)
  # FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
  CLOUD_TYPE: CDK
  AM_REALM: alpha
  # Connection settings for the IG hosted data repo
  GATEWAY_DATA_REPO_URI: http://ig:80
  IG_INTERNAL_SVC: ig
  IG_TRUSTSTORE_PATH: /secrets/truststore/igtruststore
  USER_OBJECT: user
  CERT_ISSUER: null-issuer
  
  IG_TEST_DIRECTORY_ENABLED: "true"
  IG_TEST_DIRECTORY_CA_KEYSTORE_PATH: /secrets/test-trusted-directory/test-trusted-dir-keystore.p12
  IG_TEST_DIRECTORY_CA_KEYSTORE_TYPE: PKCS12
  IG_TEST_DIRECTORY_CA_KEYSTORE_ALIAS: ca
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_PATH: /secrets/test-trusted-directory/test-trusted-dir-keystore.p12
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_TYPE: PKCS12
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_ALIAS: jwt-signer
