namespace: dev-core
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../defaults

patchesJson6902:
  - path: secrets-prometheus-patch.yaml
    target:
      kind: Secret
      name: core-secrets
      version: v1

patchesStrategicMerge:
  - configmap.yaml