apiVersion: v1
kind: ConfigMap
metadata:
  name: core-deployment-config
data:
  BASE_FQDN: shaunharrisonfr-core.forgerock.financial
  IG_FQDN: sapig.shaunharrisonfr-core.forgerock.financial
  MTLS_FQDN: mtls.sapig.shaunharrisonfr-core.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.shaunharrisonfr-core.forgerock.financial