---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ig
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ig
        envFrom:
        - secretRef:
            name: core-secrets
        - configMapRef:
            name: core-deployment-config
        imagePullPolicy: Always
        volumeMounts:
          - name: new-truststore
            mountPath: /var/ig/secrets/truststore
            readOnly: true
      volumes:
        # Empty volume where the igtruststore will be created by the initContainer, it can then be mounted into the ig container
        - name: new-truststore
          emptyDir: { }
        - name: ig-truststore-pem
          secret:
            secretName: ig-truststore-pem
            optional: false