apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
data:
  BASE_FQDN: dev.forgerock.financial
  IG_FQDN: sapig.dev.forgerock.financial
  MTLS_FQDN: mtls.sapig.dev.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.dev.forgerock.financial
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model)
  # FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
  ENVIRONMENT_TYPE: CDK
  RS_INTERNAL_SVC: test-facility-bank
  # RCS connection settings for the RS API
  RS_API_URI: http://test-facility-bank:8080
  # Connection settings for the IG hosted data repo
  GATEWAY_DATA_REPO_URI: http://ig:80
  RCS_CONSENT_STORE_URI: http://remote-consent-service:8080/consent/store
  RCS_API_INTERNAL_SVC: remote-consent-service
  RCS_UI_INTERNAL_SVC: remote-consent-service-user-interface
  RCS_CONSENT_RESPONSE_JWT_SIGNINGKEYID: rcs-jwt-signer
  RCS_CONSENT_RESPONSE_JWT_ISSUER: secure-open-banking-rcs
  AM_REALM: alpha
  USER_OBJECT: user
  CERT_ISSUER: null-issuer
  OB_ASPSP_ORG_ID: 0015800001041REAAY
  OB_ASPSP_SOFTWARE_ID: YZyyZHejcCGRrWkh3OfkLI
  IG_INTERNAL_SVC: ig
  IG_TRUSTSTORE_PATH: /secrets/truststore/igtruststore
  IG_OB_ASPSP_SIGNING_KEYSTORE_PATH: /secrets/open-banking/ig-ob-signing-key.p12
  IG_OB_ASPSP_SIGNING_KEYSTORE_TYPE: PKCS12
  IG_OB_ASPSP_SIGNING_KEYSTORE_ALIAS: jwtsigner
  IG_OB_ASPSP_SIGNING_KID: sU72Qz8tTtH9W6EoG-vhEYiQTJc
  IG_TEST_DIRECTORY_ENABLED: "true"
  IG_TEST_DIRECTORY_CA_KEYSTORE_PATH: /secrets/test-trusted-directory/test-trusted-dir-keystore.p12
  IG_TEST_DIRECTORY_CA_KEYSTORE_TYPE: PKCS12
  IG_TEST_DIRECTORY_CA_KEYSTORE_ALIAS: ca
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_PATH: /secrets/test-trusted-directory/test-trusted-dir-keystore.p12
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_TYPE: PKCS12
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_ALIAS: jwt-signer
