apiVersion: apps/v1
kind: Deployment
metadata:
  name: ig
spec:
  template:
    spec:
      containers:
      - name: ig
        envFrom:
        - secretRef:
            name: ob-secrets
        - configMapRef:
            name: ob-deployment-config