namespace: dev
commonLabels:
  app.kubernetes.io/name: "forgerock"

configMapGenerator:
- name: ob-deployment-config

secretGenerator:
- name: ob-secrets

patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
  - secret.yaml
  - ingress.yaml

images:
- name: ig
  newName: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/ig
  newTag: latest


