- op: add
  path: "/spec/template/spec/containers/0/envFrom/2"
  value:
    configMapRef:
      name: ob-deployment-config
- op: add
  path: "/spec/template/spec/containers/0/envFrom/3"
  value:
    secretRef:
      name: ob-secrets