- op: add
  path: "/spec/template/spec/containers/0/envFrom/2"
  value:
    configMapRef:
      name: ob-deployment-config
- op: add
  path: "/spec/template/spec/containers/0/envFrom/3"
  value:
    secretRef:
      name: ob-secrets
- op: add
  path: "/spec/template/spec/containers/0/volumeMounts/"
  value: 
    name: ig-ob-signing-key
    mountPath: /var/ig/secrets/open-banking
    readOnly: true
- op: add
  path: "/spec/template/spec/volumes/"
  value: 
    name: ig-ob-signing-key
    secret:
      secretName: ig-ob-signing-key
      optional: false