apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  BASE_FQDN: dev.forgerock.financial
  IG_FQDN: obdemo.dev.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.dev.forgerock.financial
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model)
  # FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
  ENVIRONMENT_TYPE: CDK
  RS_INTERNAL_SVC: securebanking-openbanking-uk-rs
  RCS_API_INTERNAL_SVC: securebanking-openbanking-uk-rcs
  RCS_UI_INTERNAL_SVC: securebanking-ui-rcs-ui
  RCS_CONSENT_RESPONSE_JWT_SIGNINGKEYID: rcs-jwt-signer
  RCS_CONSENT_RESPONSE_JWT_ISSUER: secure-open-banking-rcs
  AM_REALM: alpha
  USER_OBJECT: user
  CERT_ISSUER: null-issuer
  IG_INTERNAL_SVC: ig
  IG_TRUSTSTORE_PATH: /secrets/truststore/igtruststore
  IG_OB_ASPSP_SIGNING_KEYSTORE_PATH: /secrets/open-banking/ig-ob-signing-key.p12
  IG_OB_ASPSP_SIGNING_KEYSTORE_TYPE: PKCS12
  IG_OB_ASPSP_SIGNING_KEYSTORE_ALIAS: jwtsigner
  IG_OB_ASPSP_SIGNING_KID: NTOZs+cHZSyO0p0AKPuHctl2ddc=
  IG_TEST_DIRECTORY_CA_KEYSTORE_PATH: /secrets/test-trusted-directory/test-trusted-dir-keystore.p12
  IG_TEST_DIRECTORY_CA_KEYSTORE_TYPE: PKCS12
  IG_TEST_DIRECTORY_CA_KEYSTORE_ALIAS: ca
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_PATH: /secrets/test-trusted-directory/test-trusted-dir-keystore.p12
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_TYPE: PKCS12
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_ALIAS: jwt-signer
