generatorOptions:
  disableNameSuffixHash: true
namespace: shaunharrisonfr-ob
patches:
  - path: configmap.yaml
  - path: secret.yaml
replacements:
  - source:
      fieldPath: data.IG_FQDN
      kind: ConfigMap
      name: ob-deployment-config
      version: v1
    targets:
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: sapig
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: sapig
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: ig-web
          version: v1
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: ig-web
          version: v1
  - source:
      fieldPath: data.MTLS_FQDN
      kind: ConfigMap
      name: ob-deployment-config
      version: v1
    targets:
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: mtls
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: mtls
          version: v1
  - source:
      fieldPath: metadata.namespace
      kind: ConfigMap
      name: ob-deployment-config
      version: v1
    targets:
      - fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/auth-tls-secret]
        options:
          delimiter: /
        select:
          group: networking.k8s.io
          kind: Ingress
          name: mtls
          version: v1
resources:
  - https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/_infra/kustomize/base?ref=master
replicas:
  - name: ig
    count: 1
secretGenerator:
  - name: mtls-ca-certs
    files:
      - ca.crt