generatorOptions:
  disableNameSuffixHash: true
images:
    - name: fapi-pep-rs
      newName:  europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/fapi-pep-rs
      newTag:  latest
namespace: openig-nightly-core
patches:
  - path: configmap.yaml
  - path: secret.yaml
replacements:
  - source:
      fieldPath: data.RS_FQDN
      kind: ConfigMap
      name: rs-sapig-deployment-config
      version: v1
    targets:
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: rs-sapig
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: rs-sapig
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: rs-ig-studio
          version: v1
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: rs-ig-studio
          version: v1
resources:
  - https://github.com/SecureApiGateway/secure-api-gateway-fapi-pep-rs-core/_infra/kustomize/base?ref=main
replicas:
  - name: fapi-pep-rs
    count: 1
