namespace: nightly-core
patches:
  - path: configmap.yaml
  - target:
      version: v1
      kind: Ingress
      name: mtls
    path: patch/ingress/mtls-ingress-patch.yaml
resources:
  - ../defaults
