namespace: nightly-core
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../defaults

patchesStrategicMerge:
  - configmap.yaml

patches:
  - target:
      version: v1
      kind: Ingress
      name: cmtls
    path: patch/ingress/mtls-ingress-patch.yaml