apiVersion: v1
kind: ConfigMap
metadata:
  name: test-trusted-directory-config
data:
  IG_FQDN: "sapig.shaunharrisonfr-core.forgerock.financial"
  IDENTITY_PLATFORM_FQDN: "iam.shaunharrisonfr-core.forgerock.financial"