namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- https://github.com/ForgeRock/forgeops/kustomize/base/ingress?ref=release/7.1.0
- https://github.com/ForgeRock/forgeops/kustomize/base/ig?ref=release/7.1.0


secretGenerator:
- name: obri-ca
  files:
  - ca.crt
generatorOptions:
  disableNameSuffixHash: true
