apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  BASE_FQDN: dev.forgerock.financial
  IG_FQDN: sapig.dev.forgerock.financial
  MTLS_FQDN: mtls.sapig.dev.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.dev.forgerock.financial