apiVersion: v1
kind: ConfigMap
metadata:
  name: core-deployment-config
data:
  BASE_FQDN: devops-ob.forgerock.financial
  IG_FQDN: sapig.devops-ob.forgerock.financial
  MTLS_FQDN: mtls.sapig.devops-ob.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.devops-ob.forgerock.financial
  OB_ASPSP_SOFTWARE_ID: gYcVCmFmzItBTxM4Y1cPn2
  IG_OB_ASPSP_SIGNING_KID: KT85P5YZolPsbGVmHIOCm-KgRT0
