apiVersion: v1
kind: ConfigMap
metadata:
  name: core-deployment-config
data:
  BASE_FQDN: "mariantiris-ob.forgerock.financial"
  IG_FQDN: "sapig.mariantiris-ob.forgerock.financial"
  MTLS_FQDN: "mtls.sapig.mariantiris-ob.forgerock.financial"
  IDENTITY_PLATFORM_FQDN: "iam.mariantiris-ob.forgerock.financial"
  TRUSTEDDIR_FQDN: "test-trusted-directory.mariantiris-ob.forgerock.financial"
