namespace: mariantiris-ob
patches:
  - path: core/configmap.yaml
  - path: testtrusteddir/configmap.yaml
replacements:
  - source:
      fieldPath: data.IG_FQDN
      kind: ConfigMap
      name: core-deployment-config
      version: v1
    targets:
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: sapig
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: sapig
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: ig-web
          version: v1
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: ig-web
          version: v1
  - source:
      fieldPath: data.MTLS_FQDN
      kind: ConfigMap
      name: core-deployment-config
      version: v1
    targets:
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: mtls
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: mtls
          version: v1
  - source:
      fieldPath: metadata.namespace
      kind: ConfigMap
      name: core-deployment-config
      version: v1
    targets:
      - fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/auth-tls-secret]
        options:
          delimiter: /
        select:
          group: networking.k8s.io
          kind: Ingress
          name: mtls
          version: v1
      - fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/auth-tls-secret]
        options:
          delimiter: /
        select:
          group: networking.k8s.io
          kind: Ingress
          name: test-trusted-directory
          version: v1
  - source:
      fieldPath: data.TRUSTEDDIR_FQDN
      kind: ConfigMap
      name: test-trusted-directory-config
      version: v1
    targets:
      - fieldPaths:
          - spec.rules.0.host
        select:
          group: networking.k8s.io
          kind: Ingress
          name: test-trusted-directory
          version: v1
      - fieldPaths:
          - spec.tls.0.hosts.0
        select:
          group: networking.k8s.io
          kind: Ingress
          name: test-trusted-directory
          version: v1
resources:
  - ../defaults
replicas:
  - name: ig
    count: 1
  - name: test-trusted-directory
    count: 1