{{- if eq .Values.environment.fr_platform.type "FIDC" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloud-service-account
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store 
  target:
    name: cloud-service-account
    creationPolicy: Owner  
  data:
  - secretKey: private-key
    remoteRef:
      key: {{ .Release.Namespace}}-private-key
  - secretKey: private-id
    remoteRef:
      key: {{ .Release.Namespace}}-private-id
{{ end }}