{{- if eq .Values.environment.fr_platform.type "FIDC" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: initializer-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store 
  target:
    name: initializer-secret
    creationPolicy: Owner  
  data:
  - secretKey: cdm-admin-password
    remoteRef:
      key: {{ .Release.Namespace}}-cdm-admin-password
  - secretKey: cdm-admin-user
    remoteRef:
      key: {{ .Release.Namespace}}-cdm-admin-user
{{ end }}