name: Check Json Order

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  checkcode:
    name: Check Code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PAT }}
      - name: Sort Json Files
        run: |
          npm -g install sort-json
          find ./ -name '*.json' -exec sort-json {} \;
      - name: Commit changes
        run: |
          git config user.name fropenbanking
          git config user.email obst@forgerock.com
          git add .
          git commit -m "Automated commit - Sorting json files - [skip ci]" || exit 0
          git push