name: PR - Build and Deploy
on:
  push: #Temp for testing
  pull_request:
    branches:
      - master
    paths:
      - 'core/**'
jobs:
  run_pr-template:
    name: PR - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-pr.yml@1389-standard-steps-for-workflows
    secrets: inherit
    with:
      componentName: sapig-openbanking-uk-developer-envs
      sapigType: core