name: PR - Build and Deploy
on:
  pull_request:
    branches:
      - master
    paths:
      - 'ob/**'
jobs:
  run_pr-template:
    name: PR - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-pr.yml@main
    secrets: inherit
    with:
      componentName: sapig-openbanking-uk-developer-envs
      sapigType: ob