apiVersion: v1
kind: ConfigMap
metadata:
  name: rs-sapig-deployment-config
data:
  BASE_FQDN: "bohocode-core.forgerock.financial"
  IDENTITY_PLATFORM_FQDN: "iam.bohocode-core.forgerock.financial"
  AS_FQDN: "as-sapig.bohocode-core.forgerock.financial"
  RS_FQDN: "rs-sapig.bohocode-core.forgerock.financial"
  RS_MTLS_FQDN: "rs-mtls.sapig.bohocode-core.forgerock.financial"
  TRUSTEDDIR_FQDN: "test-trusted-directory.bohocode-core.forgerock.financial"