apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  BASE_FQDN: bohocode.forgerock.financial
  IG_FQDN: obdemo.bohocode.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.bohocode.forgerock.financial
